<?php
/**
 * @file
 * Hooks and functions for the Resource Timeslots module.
 */

/**
 * Implements hook_field_info().
 */
function resource_timeslots_field_info() {
  return array(
    'resource_timeslot' => array(
      'label' => t('Resource timeslot'),
      'description' => t('This field stores start and end datetime and a resource id.'),
      'settings' => array(),
      'instance_settings' => array(
        'resource_node_type' => NULL,
      ),
      'default_widget' => 'resource_timeslot',
      'default_formatter' => 'resource_timeslot_text',
    ),
  );
}

/**
 * Implements hook_field_instance_settings_form().
 */
function resource_timeslots_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];
  $current_type = arg(4);
  $node_types = node_type_get_names();
  unset($node_types[$current_type]);

  $form['resource_node_type'] = array(
    '#type' => 'select',
    '#title' => t('Resource content type'),
    '#default_value' => isset($settings['resource_node_type']) ? $settings['resource_node_type'] : NULL,
    '#options' => $node_types,
    '#required' => TRUE,
    '#weight' => -1,
    '#description' => t('Changing this value is not recommended, if you already have data in this field.'),
  );

  return $form;
}

/**
 * Implements hook_field_is_empty().
 */
function resource_timeslots_field_is_empty($item, $field) {
  if (empty($item['resource_id']) || empty($item['data']) || $item['data'] == '[]') {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_field_widget_info().
 */
function resource_timeslots_field_widget_info() {
  return array(
    'resource_timeslot_fc' => array(
      'label' => t('Timeslot Fullcalendar'),
      'field types' => array('resource_timeslot'),
      'settings' => array(
        'default_resource' => NULL,
        'min_slot_size' => '01:00',
        'business_hours_constrain' => FALSE,
        'business_hours' => array(),
        'max_future_months' => 3,
        'min_avail_delay_days' => 1,
        'additional_reserved_url' => NULL,
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function resource_timeslots_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  if ($widget['type'] == 'resource_timeslot_fc') {
    $form = array();
    // A bit problematic: resource type is part of the same form.
    $resource_options = array();
    if (!empty($instance['settings']['resource_node_type'])) {
      $type = $instance['settings']['resource_node_type'];
      $resource_options = _resource_timeslots_get_node_options($type);
    }
    $form['default_resource'] = array(
      '#type' => 'select',
      '#title' => t('Default resource'),
      '#options' => $resource_options,
      '#default_value' => $settings['default_resource'],
      '#empty_option' => t('None'),
    );
    if (empty($instance['settings']['resource_node_type'])) {
      $form['default_resource']['#description'] = t('This setting will be available after the Resource content type has been set.');
    }
    $slot_options = array(
      '00:30' => t('30 min'),
      '01:00' => t('1 hour'),
      '02:00' => t('2 hours'),
      '04:00' => t('4 hours'),
      '24:00' => t('1 day'),
    );
    $form['min_slot_size'] = array(
      '#type' => 'select',
      '#title' => t('Minimum slot size'),
      '#default_value' => $settings['min_slot_size'],
      '#options' => $slot_options,
      '#description' => t('If you choose "1 day", the calendar displays a full month, otherwise it displays a week.'),
    );
    $form['business_hours_constrain'] = array(
      '#type' => 'checkbox',
      '#title' => t('Constrain slots to business hours'),
      '#default_value' => $settings['business_hours_constrain'],
    );
    $form['business_hours'] = array(
      '#type' => 'fieldset',
      '#title' => t('Business hours'),
      '#states' => array(
        'visible' => array(
          ':input[name="instance[widget][settings][business_hours_constrain]"]' => array('checked' => TRUE),
        ),
      ),
    );
    $day_options = _resource_timeslots_map_day_options();
    $form['business_hours']['dow'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Days of week'),
      '#options' => $day_options,
      '#default_value' => isset($settings['business_hours']['dow']) ? $settings['business_hours']['dow'] : array(),
    );
    $form['business_hours']['start'] = array(
      '#type' => 'number',
      '#title' => t('First hour'),
      '#min' => 0,
      '#max' => 23,
      '#default_value' => isset($settings['business_hours']['start']) ? $settings['business_hours']['start'] : NULL,
    );
    $form['business_hours']['end'] = array(
      '#type' => 'number',
      '#title' => t('Last hour'),
      '#min' => 1,
      '#max' => 24,
      '#default_value' => isset($settings['business_hours']['end']) ? $settings['business_hours']['end'] : NULL,
    );
    $form['min_avail_delay_days'] = array(
      '#type' => 'number',
      '#title' => t('Min availability delay'),
      '#min' => 0,
      '#max' => 30,
      '#default_value' => $settings['min_avail_delay_days'],
      '#field_suffix' => t('days'),
      '#description' => t('How many days from current date time slot availability starts.'),
    );
    $form['max_future_months'] = array(
      '#type' => 'number',
      '#title' => t('Max available future months'),
      '#min' => 1,
      '#max' => 24,
      '#default_value' => $settings['max_future_months'],
      '#field_suffix' => t('months'),
      '#description' => t('How many months from current date slot availability ends.'),
    );
    $form['additional_reserved_url'] = array(
      '#type' => 'textfield',
      '#title' => t('URL for additional reserved slots'),
      '#default_value' => isset($settings['additional_reserved_url']) ? $settings['additional_reserved_url'] : '',
      '#description' => t('Full URL to a json feed with additional reserved slots. Use <code>{ID}</code> as placeholder for the resource ID.'),
    );

    return $form;
  }
}

/**
 * Implements hook_field_widget_form().
 */
function resource_timeslots_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'resource_timeslot_fc':
      $widget_settings = $instance['widget']['settings'];
      $dateonly = ($widget_settings['min_slot_size'] == '24:00') ? TRUE : FALSE;
      $skip_item = NULL;
      if (!empty($form['nid'])) {
        // One of the show-stoppers for multi-value fields.
        $skip_item = $form['nid']['#value'];
      }
      $reserved = _resource_timeslots_get_reserved($field['field_name'], $dateonly, $skip_item);
      $valid_range = _resource_timeslots_valid_range($widget_settings['min_avail_delay_days'], $widget_settings['max_future_months']);
      $limit = ($field['cardinality'] == FIELD_CARDINALITY_UNLIMITED) ? 100 : $field['cardinality'];
      $js_settings = array(
        'reserved' => $reserved,
        'maxValues' => $limit,
        'minSlotSize' => $widget_settings['min_slot_size'],
        'firstDay' => config_get('system.date', 'first_day'),
        'validRange' => $valid_range,
        'langCode' => _resource_timeslots_get_langcode(),
        'feedUrl' => $widget_settings['additional_reserved_url'],
      );
      // Business hours control visibility and availability.
      if ($widget_settings['business_hours_constrain']) {
        $js_settings['businessHours'] = array(
          'startTime' => str_pad($widget_settings['business_hours']['start'], 2, '0', STR_PAD_LEFT) . ':00',
          'endTime' => str_pad($widget_settings['business_hours']['end'], 2, '0', STR_PAD_LEFT) . ':00',
        );
        $days = _resource_timeslots_map_day_options($widget_settings['business_hours']['dow']);
        $js_settings['businessHours']['daysOfWeek'] = array_keys($days);
      }
      else {
        $js_settings['businessHours'] = NULL;
      }
      // Switch calendar type based on slot size setting.
      $js_settings['calendarType'] = 'timeGridWeek';
      if ($widget_settings['min_slot_size'] == '24:00') {
        $js_settings['calendarType'] = 'dayGridMonth';
      }

      $element['#attached']['js'][] = array(
        'type' => 'setting',
        'data' => array(
          'resource_timeslots_setup' => array(
            $field['field_name'] => $js_settings,
          ),
        ),
      );
      $element['#attached']['library'][] = array('resource_timeslots', 'fullcalendar');
      $element['#attached']['js'][] = backdrop_get_path('module', 'resource_timeslots') . '/js/resource-ts.js';
      $element['#attached']['css'][] = backdrop_get_path('module', 'resource_timeslots') . '/css/resource-ts.css';

      $item_id = 'fullcal-' . $field['field_name'] . '-' . $delta;
      // @todo Consider autocomplete if too many nodes?
      $type = $instance['settings']['resource_node_type'];
      $resource_options = _resource_timeslots_get_node_options($type);
      $resource_id = isset($items[$delta]['resource_id']) ? $items[$delta]['resource_id'] : '0';
      if (empty($items[$delta]['resource_id']) && !empty($widget_settings['default_resource'])) {
        if (array_key_exists($widget_settings['default_resource'], $resource_options)) {
          $resource_id = $widget_settings['default_resource'];
        }
      }
      $params = backdrop_get_query_parameters();
      $args = arg();
      // New nodes can take the $_GET parameter as resource id, which also
      // overrides the widget default value setting above.
      if (count($args) > 2 && $args[0] == 'node' && $args[1] == 'add' && !empty($params['resource-id'])) {
        if (array_key_exists($params['resource-id'], $resource_options)) {
          // Sanitize by casting to int.
          $resource_id = (int) $params['resource-id'];
        }
      }
      $title = t('Select resource');
      if (!empty($instance['settings']['resource_node_type'])) {
        $node_type = node_type_get_type($instance['settings']['resource_node_type']);
        if ($node_type) {
          $title = t('Select @nodetype', array('@nodetype' => $node_type->name));
        }
      }
      $element['resource_timeslot'] = array(
        '#type' => 'container',
        '#title' => 'test',
      );
      $element['resource_timeslot']['resource_id'] = array(
        '#type' => 'select',
        '#title' => $title,
        '#options' => $resource_options,
        '#default_value' => $resource_id,
        '#required' => $instance['required'],
        '#empty_value' => '0',
      );
      $markup = '<div id="' . $item_id . '" data-fieldname="' . $field['field_name'] . '" class="dt-range-fullcal"></div>';
      $info = t('@selected slot(s) selected, @avail remaining.', array(
        '@selected' => count($items),
        '@avail' => $limit - count($items),
      ));
      $markup .= '<details><summary>' . $info . '</summary><p></p></details>';
      $markup .= '<p class="noscript-hint js-hide">' . t('Javascript is required to use this form.') . '</p>';
      $element['resource_timeslot']['fullcalendar'] = array(
        '#type' => 'item',
        '#markup' => $markup,
        '#title' => t('Time slot'),
        '#states' => array(
          'visible' => array(
            ':input[name="' . $field['field_name'] . '[und][resource_timeslot][resource_id]"]' => array('!value' => '0'),
          ),
        ),
        '#required' => $instance['required'],
        '#wrapper_attributes' => array('class' => array('form-item-fc-slot')),
      );
      if (!empty($element['#description'])) {
        // Copy help text to the appropriate place.
        $element['resource_timeslot']['fullcalendar']['#description'] = $element['#description'];
      }
      // @todo callback?
      $values = array();
      $encoded = '[]';
      if (isset($items[0]) && array_key_exists('data', $items[0])) {
        // Back from preview, re-use already parsed data from tempstore.
        $encoded = $items[0]['data'];
      }
      else {
        foreach ($items as $delta => $item) {
          // Add dates parsable by js, using timestamp integers (msec).
          $values[$delta]['start'] = $items[$delta]['start'] * 1000;
          $values[$delta]['end'] = $items[$delta]['end'] * 1000;
        }
        $encoded = json_encode($values);
      }
      $element['resource_timeslot']['data'] = array(
        '#type' => 'hidden',
        '#default_value' => $encoded,
        '#attributes' => array('class' => array('fc-data')),
      );

      break;
  }
  return $element;
}

/**
 * Implements hook_field_validate().
 */
function resource_timeslots_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  if ($entity == NULL) {
    // We're not on a node, but rather on the field settings form.
    return;
  }
  foreach ($items as $delta => $item) {
    if ($instance['required']) {
      if (empty($item['resource_id']) || empty($item['data']) || $item['data'] == '[]') {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'resource_timeslot_empty',
          'message' => t('!name field is required.', array(
            '!name' => $instance['label'],
          )),
        );
      }
    }
    // Following two checks are for sanity, as values get set via select or js
    // and should always pass.
    if (!empty($item['resource_id']) && (int) $item['resource_id'] === 0) {
      $errors[$field['field_name']][$langcode][$delta][] = array(
        'error' => 'resource_timeslot_invalid_nid',
        'message' => t('Invalid resource value'),
      );
    }
    if (!empty($item['data']) && $item['data'] != '[]' && json_decode($item['data']) == NULL) {
      $errors[$field['field_name']][$langcode][$delta][] = array(
        'error' => 'resource_timeslot_invalid_data',
        'message' => t('Invalid data'),
      );
    }
  }
}

/**
 * Implements hook_field_presave().
 */
function resource_timeslots_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  $items_processed = array();
  if (empty($items)) {
    return $items_processed;
  }
  // One item contains all data we need.
  $data = json_decode($items[0]['data']);
  foreach ($data as $item) {
    if (is_numeric($item->start) && is_numeric($item->end)) {
      $items_processed[] = array(
        'resource_id' => $items[0]['resource_id'],
        'start' => $item->start / 1000,
        'end' => $item->end / 1000,
      );
    }
  }
  if (!empty($items_processed)) {
    // Sort by start timestamp before inserting into db.
    usort($items_processed, function($a, $b) {
      return $a['start'] - $b['start'];
    });
  }
  $items = $items_processed;
}

/**
 * Implements hook_field_formatter_info().
 */
function resource_timeslots_field_formatter_info() {
  return array(
    'resource_timeslot_text' => array(
      'label' => t('Default (text)'),
      'field types' => array('resource_timeslot'),
    ),
    'resource_timeslot_list' => array(
      'label' => t('List'),
      'field types' => array('resource_timeslot'),
    ),
    'resource_timeslot_table' => array(
      'label' => t('Table'),
      'field types' => array('resource_timeslot'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function resource_timeslots_theme($existing, $type, $theme, $path) {
  $themes = array(
    'resource_timeslot_oneliner' => array(
      'file' => 'resource_timeslots.theme.inc',
      'path' => $path,
      'render element' => 'element',
    ),
    'resource_timeslot_list' => array(
      'file' => 'resource_timeslots.theme.inc',
      'path' => $path,
      'render element' => 'element',
    ),
    'resource_timeslot_table' => array(
      'file' => 'resource_timeslots.theme.inc',
      'path' => $path,
      'render element' => 'element',
    ),
  );

  return $themes;
}

/**
 * Implements hook_field_formatter_view().
 */
function resource_timeslots_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  if (empty($items)) {
    return $element;
  }
  if (array_key_exists('data', $items[0])) {
    $message = t('Field %label does not support dynamic previews.', array(
      '%label' => $instance['label'],
    ));
    $element[0] = array(
      '#type' => 'markup',
      '#markup' => '<p>' . $message . '</p>',
    );
    return $element;
  }
  switch ($display['type']) {
    case 'resource_timeslot_text':
      foreach ($items as $delta => $item) {
        $markup = theme('resource_timeslot_oneliner', array('item' => $item));
        $element[$delta] = array('#markup' => $markup);
      }
      break;

    case 'resource_timeslot_list':
      foreach ($items as $delta => $item) {
        $markup = theme('resource_timeslot_list', array('item' => $item));
        $element[$delta] = array('#markup' => $markup);
      }
      break;

    case 'resource_timeslot_table':
      $markup = theme('resource_timeslot_table', array('items' => $items));
      $element[0] = array(
        '#type' => 'markup',
        '#markup' => $markup,
      );
      break;

  }
  return $element;
}

/**
 * Implements hook_field_views_data_views_data_alter().
 */
function resource_timeslots_field_views_data_views_data_alter(&$data, $field) {
  if ($field['type'] == 'resource_timeslot') {
    $field_name = $field['field_name'];
    $data_table_name = 'field_data_' . $field_name;
    $revision_table_name = 'field_revision_' . $field_name;

    // Inform views that our field columns are dates (timestamps).
    $data[$data_table_name][$field_name . '_start']['field']['handler'] = 'views_handler_field_date';
    $data[$data_table_name][$field_name . '_end']['field']['handler'] = 'views_handler_field_date';
    $data[$data_table_name][$field_name . '_start']['filter']['handler'] = 'views_handler_filter_date';
    $data[$data_table_name][$field_name . '_start']['sort']['handler'] = 'views_handler_sort_date';
    $data[$data_table_name][$field_name . '_end']['filter']['handler'] = 'views_handler_filter_date';
    $data[$data_table_name][$field_name . '_end']['sort']['handler'] = 'views_handler_sort_date';
    // Relationship to the node table.
    $data[$data_table_name]['table']['group'] = t('Content');
    $data[$data_table_name][$field_name . '_resource_id']['relationship'] = array(
      'base' => 'node',
      'base field' => 'nid',
      'handler' => 'views_handler_relationship',
      'title' => 'Resource node',
      'label' => 'Resource node',
      'help' => 'Related resource nodes',
    );
  }
}

/**
 * Implements hook_library_info().
 */
function resource_timeslots_library_info() {
  $path = backdrop_get_path('module', 'resource_timeslots') . '/libraries/fullcalendar/lib';
  $libraries['fullcalendar'] = array(
    'title' => 'Fullcalendar recent',
    'website' => 'https://fullcalendar.io',
    'version' => '5.10.1',
    'js' => array(
      $path . '/main.min.js' => array(),
      $path . '/locales-all.min.js' => array(),
    ),
    'css' => array($path . '/main.min.css' => array()),
  );
  return $libraries;
}

/**
 * Helper function.
 *
 * @param string $field_name
 *   Field machine name.
 * @param bool $dateonly
 *   Return timeless dates if set to TRUE, full datetime otherwiese.
 * @param string $skip
 *   Do not add this entity (nid) to the results, usually the current one.
 *
 * @return array
 *   Keyed array of dates, to be used as Fullcalendar events.
 */
function _resource_timeslots_get_reserved($field_name, $dateonly = FALSE, $skip = NULL) {
  $reserved = &backdrop_static(__FUNCTION__);

  if (!isset($reserved)) {
    $reserved = array();
    $db_table = 'field_data_' . $field_name;
    $col_end = $field_name . '_end';
    $query = db_select($db_table, 't');
    $query->join('node', 'n', 'n.nid = t.entity_id');
    $query->fields('t')
      ->condition('n.status', 1)
      ->condition('deleted', '0')
      ->condition($col_end, REQUEST_TIME, '>');

    if (isset($skip)) {
      $query->condition('entity_id', $skip, '!=');
    }
    $results = $query->execute()->fetchAll();

    if (empty($results)) {
      return $reserved;
    }

    $col_start = $field_name . '_start';
    $col_nid = $field_name . '_resource_id';
    $date_pattern = ($dateonly) ? 'Y-m-d' : 'c';

    foreach ($results as $index => $item) {
      $reserved[$item->{$col_nid}][] = array(
        'start' => format_date($item->{$col_start}, 'custom', $date_pattern),
        'end' => format_date($item->{$col_end}, 'custom', $date_pattern),
        'display' => 'background',
      );
    }
  }

  return $reserved;
}

/**
 * Custom helper function to get node type options.
 *
 * @param string $type
 *   Node type name.
 */
function _resource_timeslots_get_node_options($type) {
  $nodes = &backdrop_static(__FUNCTION__);
  if (!isset($nodes)) {
    // Does not work with translated nodes (different nid).
    $query = 'SELECT nid, title FROM {node} WHERE TYPE = :type AND status = 1 ORDER BY title ASC;';
    $result = db_query($query, array(':type' => $type))->fetchAllAssoc('nid');
    $nodes = array();
    foreach ($result as $nid => $item) {
      $nodes[$nid] = $item->title;
    }
  }
  return $nodes;
}

/**
 * Helper function to return the valid range for Fullcalendar.
 *
 * @param string $delay_days
 *   Number of days to delay from today.
 * @param string $future_months
 *   Number of months that should be available.
 *
 * @return array
 *   Keyed array for range start and end.
 */
function _resource_timeslots_valid_range($delay_days, $future_months) {
  $range_start = new BackdropDateTime();
  $range_start->modify('+' . $delay_days . ' days');
  $range_end = new BackdropDateTime();
  $range_end->modify('+' . $future_months . ' months');
  $valid_range = array(
    'start' => $range_start->format('Y-m-d'),
    'end' => $range_end->format('Y-m-d'),
  );

  return $valid_range;
}

/**
 * Helper function for day mappings.
 *
 * Checkboxes form items do not reliably save numeric keys, Fullcalendar needs
 * numbers, so we have to translate.
 *
 * @param array $map_array
 *   Settings array (from config) to translate to number keys.
 */
function _resource_timeslots_map_day_options($map_array = NULL) {
  if (!isset($map_array)) {
    $days = array(
      'mon' => t('Monday'),
      'tue' => t('Tuesday'),
      'wed' => t('Wednesday'),
      'thu' => t('Thursday'),
      'fri' => t('Friday'),
      'sat' => t('Saturday'),
      'sun' => t('Sunday'),
    );
    return $days;
  }
  elseif (is_array($map_array)) {
    $mapping = array(
      'mon' => 1,
      'tue' => 2,
      'wed' => 3,
      'thu' => 4,
      'fri' => 5,
      'sat' => 6,
      'sun' => 0,
    );
    $numbers = array();
    $active = array_filter($map_array);
    foreach ($mapping as $shortname => $number) {
      if (array_key_exists($shortname, $active)) {
        $numbers[$number] = $shortname;
      }
    }
    return $numbers;
  }

  return FALSE;
}

/**
 * Helper function to return the langcode.
 *
 * @see https://github.com/backdrop-contrib/resource_timeslots/issues/8
 */
function _resource_timeslots_get_langcode() {
  global $language;
  $langcode = $language->langcode;
  $default_country = config_get('system.date', 'default_country');

  // Otherwise people in UK get the wrong date/month order in calendar headers.
  if ($default_country == 'GB' && $langcode == 'en') {
    return 'en-gb';
  }

  return $langcode;
}
